/**
 * End-to-end tests for the suggest-clips API and accept-suggestion flow.
 *
 * The video source is generated by the real FFmpeg binary with three
 * distinct color scenes, so scene changes are guaranteed to be detected.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import type { AddressInfo } from 'node:net';
import type { Server } from 'node:http';
import { rmSync, readFileSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { Application } from 'express';

const dataDir = mkdtempSync(path.join(tmpdir(), 'clipforge-suggest-'));
process.env.CLIPFORGE_DATA_DIR = dataDir;
process.env.CLIPFORGE_DB = path.join(dataDir, 'clipforge.db');
process.env.PORT = '0';
process.env.CLIPFORGE_START = '0';

const { createApp } = await import('../server/index.ts');
const { runFfmpeg } = await import('../server/media/ffmpeg-runner.ts');
const { probeFfmpeg } = await import('../server/media/ffmpeg-locator.ts');

const ffmpeg = probeFfmpeg();
if (!ffmpeg.available) {
  throw new Error(
    `FFmpeg is required for the suggest-clips API tests but is unavailable: ${ffmpeg.reason}. ` +
      'Run `npm run setup:ffmpeg`.',
  );
}

let server: Server | null = null;
let baseUrl = '';
const cookies: string[] = [];

const app: Application = createApp();

test.after(() => {
  if (server) {
    server.close();
    server = null;
  }
  rmSync(dataDir, { recursive: true, force: true });
});

test.before(async () => {
  await new Promise<void>((resolve) => {
    server = app.listen(0, '127.0.0.1', () => resolve());
  });
  const addr = server!.address() as AddressInfo;
  baseUrl = `http://127.0.0.1:${addr.port}`;
});

async function api<T = unknown>(
  method: string,
  urlPath: string,
  body?: unknown,
): Promise<{ status: number; body: T }> {
  const init: RequestInit = { method };
  const headers: Record<string, string> = {};
  if (cookies.length) headers.cookie = cookies.join('; ');
  if (body !== undefined) {
    if (body instanceof FormData) {
      init.body = body;
    } else {
      headers['content-type'] = 'application/json';
      init.body = JSON.stringify(body);
    }
  }
  init.headers = headers;
  const res = await fetch(`${baseUrl}${urlPath}`, init);
  const setCookie = res.headers.get('set-cookie');
  if (setCookie) cookies.push(setCookie.split(';')[0]!);
  const text = await res.text();
  let parsed: T = undefined as T;
  if (text) {
    try {
      parsed = JSON.parse(text) as T;
    } catch {
      parsed = text as T;
    }
  }
  return { status: res.status, body: parsed };
}

async function makeSourceVideo(): Promise<string> {
  // 8 seconds: red 2s, blue 2s, green 2s, red 2s. Plus an audio sine
  // so silence detection has something to chew on.
  const out = path.join(dataDir, 'source.mp4');
  await runFfmpeg([
    '-hide_banner', '-y',
    '-f', 'lavfi', '-i', 'color=c=red:size=320x240:rate=15:duration=2',
    '-f', 'lavfi', '-i', 'color=c=blue:size=320x240:rate=15:duration=2',
    '-f', 'lavfi', '-i', 'color=c=green:size=320x240:rate=15:duration=2',
    '-f', 'lavfi', '-i', 'color=c=red:size=320x240:rate=15:duration=2',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=8',
    '-filter_complex',
      '[0:v]setpts=PTS-STARTPTS[v0];' +
      '[1:v]setpts=PTS-STARTPTS[v1];' +
      '[2:v]setpts=PTS-STARTPTS[v2];' +
      '[3:v]setpts=PTS-STARTPTS[v3];' +
      '[v0][v1][v2][v3]concat=n=4:v=1:a=0[outv];' +
      '[4:a]aresample=44100[a0]',
    '-map', '[outv]', '-map', '[a0]',
    '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-preset', 'ultrafast',
    '-c:a', 'aac', '-shortest', '-r', '15',
    out,
  ]);
  return out;
}

async function uploadSource(): Promise<string> {
  const localSrc = await makeSourceVideo();
  const form = new FormData();
  form.append(
    'video',
    new Blob([readFileSync(localSrc)], { type: 'video/mp4' }),
    'scene-source.mp4',
  );
  const r = await api<{ project?: { id: string } }>('POST', '/api/projects', form);
  assert.equal(r.status, 201, JSON.stringify(r.body));
  assert.ok(r.body.project?.id, 'no project id');
  return r.body.project.id;
}

async function pollClip(
  clipId: string,
  timeoutMs = 60_000,
): Promise<{ status: string; output: unknown }> {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const r = await api<{ clip: { status: string; output: unknown } }>(
      'GET',
      `/api/clips/${clipId}`,
    );
    if (r.body.clip.status === 'completed' || r.body.clip.status === 'failed') {
      return r.body.clip;
    }
    await new Promise((r) => setTimeout(r, 500));
  }
  throw new Error(`clip ${clipId} did not complete within ${timeoutMs}ms`);
}

test('GET /api/projects/:id/suggest-clips returns real candidates', async () => {
  const projectId = await uploadSource();
  const r = await api<{
    candidates: Array<{ startSeconds: number; durationSeconds: number; score: number; reason: string; signals: string[] }>;
    rawSceneChangeCount: number;
    rawSilenceCount: number;
  }>('GET', `/api/projects/${projectId}/suggest-clips?sceneThreshold=0.1&minDuration=2&maxDuration=6`);
  assert.equal(r.status, 200);
  assert.ok(r.body.rawSceneChangeCount >= 1, 'expected at least one scene change');
  assert.ok(r.body.candidates.length >= 1, 'expected at least one candidate');
  for (const c of r.body.candidates) {
    assert.ok(c.startSeconds >= 0);
    assert.ok(c.durationSeconds > 0);
    assert.ok(c.score >= 0 && c.score <= 1);
    assert.ok(c.reason.length > 0);
    assert.ok(Array.isArray(c.signals));
  }
});

test('suggest-clips honours minDuration and maxDuration query params', async () => {
  const projectId = await uploadSource();
  const r = await api<{
    candidates: Array<{ durationSeconds: number }>;
  }>(
    'GET',
    `/api/projects/${projectId}/suggest-clips?minDuration=2&maxDuration=4`,
  );
  assert.equal(r.status, 200);
  for (const c of r.body.candidates) {
    assert.ok(c.durationSeconds >= 2, `candidate too short: ${c.durationSeconds}`);
    assert.ok(c.durationSeconds <= 4, `candidate too long: ${c.durationSeconds}`);
  }
});

test('suggest-clips rejects minDuration >= maxDuration', async () => {
  const projectId = await uploadSource();
  const r = await api('GET', `/api/projects/${projectId}/suggest-clips?minDuration=10&maxDuration=5`);
  assert.equal(r.status, 400);
});

test('suggest-clips requires a real project id', async () => {
  const r = await api('GET', '/api/projects/not-a-uuid/suggest-clips');
  assert.equal(r.status, 400);
});

test('suggest-clips returns 404 for a missing project', async () => {
  const r = await api(
    'GET',
    '/api/projects/00000000-0000-0000-0000-000000000000/suggest-clips',
  );
  assert.equal(r.status, 404);
});

test('suggest-clips caps the number of returned candidates at "max"', async () => {
  const projectId = await uploadSource();
  const r = await api<{ candidates: unknown[] }>(
    'GET',
    `/api/projects/${projectId}/suggest-clips?max=2`,
  );
  assert.equal(r.status, 200);
  assert.ok(r.body.candidates.length <= 2);
});

test('accepting a suggestion creates and renders a real clip', async () => {
  const projectId = await uploadSource();
  const suggestions = await api<{
    candidates: Array<{ startSeconds: number; durationSeconds: number; score: number; reason: string }>;
  }>('GET', `/api/projects/${projectId}/suggest-clips?sceneThreshold=0.1&minDuration=2&maxDuration=6`);
  assert.equal(suggestions.status, 200);
  assert.ok(suggestions.body.candidates.length >= 1);
  const cand = suggestions.body.candidates[0]!;
  const r = await api<{ clip: { id: string; status: string } }>(
    'POST',
    `/api/projects/${projectId}/clips/from-suggestion`,
    {
      title: 'Auto-' + cand.reason,
      startSeconds: cand.startSeconds,
      durationSeconds: cand.durationSeconds,
      aspect: 'vertical',
    },
  );
  assert.equal(r.status, 201, JSON.stringify(r.body));
  assert.ok(r.body.clip.id);
  const final = await pollClip(r.body.clip.id);
  assert.equal(final.status, 'completed');

  // The clip must be downloadable as a real MP4.
  const head = await fetch(`${baseUrl}/api/clips/${r.body.clip.id}/output`);
  assert.equal(head.status, 200);
  const buf = new Uint8Array(await head.arrayBuffer());
  assert.equal(
    String.fromCharCode(...buf.slice(4, 8)),
    'ftyp',
    'output is not a real MP4',
  );
});

test('accepting a suggestion with an invalid segment is rejected', async () => {
  const projectId = await uploadSource();
  const r = await api(
    'POST',
    `/api/projects/${projectId}/clips/from-suggestion`,
    {
      title: 'bad',
      startSeconds: -1,
      durationSeconds: 5,
      aspect: 'vertical',
    },
  );
  assert.equal(r.status, 400);
});

test('suggest-clips never returns candidates beyond the source duration', async () => {
  const projectId = await uploadSource();
  const proj = await api<{ project: { media: { durationSeconds: number | null } } }>(
    'GET',
    `/api/projects/${projectId}`,
  );
  const dur = proj.body.project.media.durationSeconds ?? 0;
  const r = await api<{ candidates: Array<{ startSeconds: number; durationSeconds: number }> }>(
    'GET',
    `/api/projects/${projectId}/suggest-clips`,
  );
  assert.equal(r.status, 200);
  for (const c of r.body.candidates) {
    assert.ok(
      c.startSeconds + c.durationSeconds <= dur + 0.1,
      `candidate ${c.startSeconds}+${c.durationSeconds} exceeds source ${dur}`,
    );
  }
});

test('user-controlled query values cannot become arbitrary FFmpeg args', async () => {
  // The route clamps query values to numeric ranges, so even hostile
  // strings like "1; rm -rf /" should be either rejected or parsed as
  // a clamped number. The output is still a deterministic candidate set.
  const projectId = await uploadSource();
  const evil = encodeURIComponent("1; rm -rf $(pwd) `id` '\"$IFS\"'");
  const r = await api(
    'GET',
    `/api/projects/${projectId}/suggest-clips?sceneThreshold=${evil}&silenceDb=${evil}`,
  );
  // 200 with the bogus value treated as a number (NaN -> fallback) OR 400.
  assert.ok(r.status === 200 || r.status === 400, `unexpected status ${r.status}`);
  // Canary: nothing got deleted.
  const canary = path.join(dataDir, 'canary.txt');
  writeFileSync(canary, 'untouched');
  // Re-run a normal request; ffmpeg should still work.
  const r2 = await api('GET', `/api/projects/${projectId}/suggest-clips`);
  assert.equal(r2.status, 200);
  assert.equal(readFileSync(canary, 'utf8'), 'untouched', 'shell injection occurred');
});
